In [9]:
import numpy as np
import xarray as xr
import rioxarray
from shapely.geometry import box, Point
from rasterio.enums import Resampling

values = np.arange(20, dtype="float32").reshape(4, 5)

toy = xr.DataArray(
    values,
    dims=("y", "x"),
    coords={
        "y": [8950035.0, 8950025.0, 8950015.0, 8950005.0],   # centri dei pixel, da nord a sud
        "x": [580005.0, 580015.0, 580025.0, 580035.0, 580045.0],
    },
    name="toy",
)
toy = toy.rio.write_crs("EPSG:32720")
toy

<xarray.DataArray 'toy' (y: 4, x: 5)> Size: 80B
array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]], dtype=float32)
Coordinates:
  * y            (y) float64 32B 8.95e+06 8.95e+06 8.95e+06 8.95e+06
  * x            (x) float64 40B 5.8e+05 5.8e+05 5.8e+05 5.8e+05 5.8e+05
    spatial_ref  int64 8B 0

In [2]:
toy.rio.resolution()

(10.0, -10.0)

In [3]:
toy.rio.bounds()

(580000.0, 8950000.0, 580050.0, 8950040.0)

In [4]:
toy.rio.transform()

Affine(10.0, 0.0, 580000.0,
       0.0, -10.0, 8950040.0)

In [5]:
wrong = toy.rio.write_crs("EPSG:4326", inplace=False)

In [6]:
wrong.rio.bounds()

(580000.0, 8950000.0, 580050.0, 8950040.0)

In [10]:
coarse_nearest = toy.rio.reproject(toy.rio.crs, resolution=20)
coarse_average = toy.rio.reproject(toy.rio.crs, resolution=20,
                                   resampling=Resampling.average)

print(coarse_nearest.shape)
print(coarse_nearest.values)
print()
print(coarse_average.values)

(2, 3)
[[ 6.  8. nan]
 [16. 18. nan]]

[[ 3.   5.   6.5]
 [13.  15.  16.5]]
